import './globals.css'; // Importa tus estilos globales

export const metadata = {
  title: 'My App',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* Aquí puedes agregar una barra de navegación, footer, etc. */}
        {children} {/* El contenido de las páginas se renderizará aquí */}
      </body>
    </html>
  );
}